### ISSUE TITLE
Ezy-Parking : Create the Carousel for the Home Page

### ISSUE THREAD

**Issue by itshypon** [prathimacode-hub/Ezy-Parking#10]
---
Title: Create the Carousel for the Home Page
About: Words at carousel is not quite visible so I will fix it with some minor typing errors
Name: Himanshu
Label: Bug Report
Assignee: ''

---

Define You:

- [x] Hacktoberfest Participant
- [ ] Contributor

Yes

**Describe the Bug**

At homepage of website, we see that some words on carousel are not quite visible so they need some changes

**Steps to Reproduce**

1. Go to Ezy-parking website
2. Go to home tab (Main webpage)
3. See the carousel picture and words on it

**Expected Behavior**

Picture should be more user-interactive with words clearly visible on it

**Actual Behavior**

Words are not quite visible on it and image doesn't look well on it

**Screenshots/Block Diagram/Emulator Prototype Diagram**

![image](https://user-images.githubusercontent.com/30335924/193579244-0b1293f2-e0dd-4231-a9b2-285725ef5676.png)

**Comment by prathimacode-hub** [comment]
Can you come up with the valid issue? This is so minor. @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub Words inside pictures are not clearly visible also. Can adjust the photo slides and text inside it which will look better to user.

**Comment by prathimacode-hub** [comment]
Prepare a complete end to end carousel for the webapp. Do the changes in issue description to get assigned. @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub done

**Comment by prathimacode-hub** [comment]
You are mentioning as minor mistake instead say it as a carousel. Don't include minor mistake thing in issue description even though you do it as part of the issue. @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub Okay, thanks for the info.

**Comment by prathimacode-hub** [comment]
Add an issue template and include the issue description into it. You can find them in the repo. Read the contributing guidelines and README file. @itshypon

**Comment by prathimacode-hub** [comment]
Issue assigned to @itshypon

**Comment by prathimacode-hub** [comment]
Update please? @itshypon

**Comment by itshypon** [comment]
@prathimacode-hub Sorry, was busy with other stuff. Will submit this week, if you want this early I can do that also.

**Comment by lemostrash** [comment]
@prathimacode-hub can i assign a solution to this problem?

**Comment by prathimacode-hub** [comment]
@itshypon, Update please? 

Let's wait for the response from other, before it's assigned to you. @lemostrash

**Comment by lemostrash** [comment]
@prathimacode-hub Okay :)

**Comment by lemostrash** [comment]
@prathimacode-hub Okay :)

**Comment by itshypon** [comment]
@prathimacode-hub Sent PR, kindly check. If navigation bar doesn't look quite visible, it can be added in another issue and given to another person who want try out some easy task.
