### ISSUE TITLE
Make some Changes in the Design of the Website

### ISSUE THREAD

**Issue by ayushmangarg2003** [prathimacode-hub/Ezy-Parking#14]
I would Like to change to color of the navbar . Also I will make some Changes in the testimonial Section.

**Comment by ayushmangarg2003** [comment]
I will surely follow code of conduct and I am starting working on the issue

**Comment by prathimacode-hub** [comment]
Kindly follow contributing guidelines. Add issue template, elaborate and be specific with issue title. Also, you can add 2 more changes to it with respect to the design. @ayushmangarg2003

**Comment by ayushmangarg2003** [comment]
Sorry , from next time I will take care about the issue template ,  Can you please elaborate about the changes you are talking about

**Comment by prathimacode-hub** [comment]
What's the change you would like to add, list it using the issue template provided so that i can assign it. @ayushmangarg2003
