### ISSUE TITLE
Client side validation during login and sign up

### ISSUE THREAD

**Issue by 1Fetcher** [prathimacode-hub/Ezy-Parking#17]
---
Title: Client side validation during login and sign up needs to be added
About: There is no client side validation during login and signup, I can add validation 
Name: Sudhir
Label: Bug Report
Assignee: ''

---

Define You:

- [x] Hacktoberfest Participant
- [ ] Contributor

**Describe the Bug**
There is no client side validation during login and signup

**Steps to Reproduce**
Just submit the login or sign up form.

1. Click the Register/Log button from header section of the site 
2. Submit the form 
3. Click the sign up link from the login page (above login form)
4. Submit the sign up form

**Expected Behavior**
Forms should display the proper validation errors

**Actual Behavior**
There is no validation errors after form submit. 

**Screenshots/Block Diagram/Emulator Prototype Diagram**

**Additional Details**

**Comment by prathimacode-hub** [comment]
Issue assigned to @1Fetcher
