### ISSUE TITLE
UI for user parking suggestions [New page]

### ISSUE THREAD

**Issue by 1Fetcher** [prathimacode-hub/Ezy-Parking#18]
---
Title: UI for parking suggestions [New page]
About: After this feature, users will be able to set their current location and check nearby parking spaces on the map with the following details
1. Parking spot name
2. Empty / Occupied parking spot counter
3. Nearby Events on the map

Name: Sudhir Kumar Verma
Label: Feature Request
Assignee: ''

---

Define You:

- [x] Hacktoberfest Participant 
- [x] Contributor

**Approach to be followed (optional):**

1. New link in the header of the site with the label *Check Parking* (Suggest if another label is required)
  1.1. After the Page loads it will request location permission 
3. Page will contain the following sections
  2.1. Input field [text] (for getting address or Pincode from the user) 
  2.2. *Use Current Location* Button (For getting the user's current location) (Suggest if another label is required)
  2.3. Render map with user location and available nearby parking spots and events
  2.4. Listing of available nearby parking spots and events

**Comment by prathimacode-hub** [comment]
Issue assigned to @1Fetcher

**Comment by prathimacode-hub** [comment]
Update please? @1Fetcher

**Comment by 1Fetcher** [comment]
> Update please? @1Fetcher 

Will update on next sunday evening 🙃.

**Comment by prathimacode-hub** [comment]
Hacktober fest ends tomorrow. Hope you know that. It won't be counted if it's later to it. @1Fetcher

**Comment by 1Fetcher** [comment]
> Hacktober fest ends tomorrow. Hope you know that. It won't be counted if it's later to it. @1Fetcher 

Yes i know that and I have completed my hacktoberfest PRs  🙃🤩, 
Now it's not about hacktoberfest anymore I will try my level best to contribute in this project 🙃. 

Thank you so much for giving me opportunity to contribute in this awesome project.

🙏
🙃👍

**Comment by prathimacode-hub** [comment]
Most welcome and understood. Go ahead. ✔👌@1Fetcher

**Comment by 1Fetcher** [comment]
> Most welcome and understood. Go ahead. ✔👌@1Fetcher 

I am integrating Google map to display nearby parking spot and events.

But for that first I need an API from where I get the details of near by parking spots and events based on user location. 🤔

**Comment by prathimacode-hub** [comment]
@1Fetcher, I just check your message. Didn't notice earlier.
