### ISSUE TITLE
Fixing the padding in the mobile view of the website

### ISSUE THREAD

**Issue by CS50X-RGB** [prathimacode-hub/Ezy-Parking#25]
About: Padding problem in mobile view
 Name: Rohan Chatterjee
 Label: Bug Report
 --- 
  
 Define You: 
  
 - [x] KWOC Participant 
 - [x] Contributor 
  
  
  Have you talked to any of the Moderators or Project Admin (Prathima Kadari) before creating this issue? If not, just have a quick discussion and then once approved, create this issue. 
Yes
  
 **Describe the Bug** 
  Padding issue 
  
  
 **Steps to Reproduce** 
  
 Steps to reproduce the behavior: 
  
 1. Work on media queries. 
 2.  Remove some padding 
  
 **Expected Behavior** 
  
  
  
 **Remove the padding in media queries of 520 px** 
  
  
  
 **Screenshots/Block Diagram/Emulator Prototype Diagram** 
![image](https://user-images.githubusercontent.com/89659393/207604820-c96785e0-eef0-4555-b28e-e6e6a1efb096.png)

**Comment by prathimacode-hub** [comment]
@CS50X-RGB, Add the issue information along with issue template provided.

**Comment by CS50X-RGB** [comment]
> @CS50X-RGB, Add the issue information along with issue template provided.

Okay working on it

**Comment by CS50X-RGB** [comment]
@prathimacode-hub Done

**Comment by prathimacode-hub** [comment]
Template has been automated now. You can create a new issue using it. @CS50X-RGB

**Comment by CS50X-RGB** [comment]
@prathimacode-hub an delete this  issue plz i guess only the admin can delete an issue

**Comment by prathimacode-hub** [comment]
You can use edit option to do the changes @CS50X-RGB
