### ISSUE TITLE
Ezy-Parking : Create the Testimonials section for the Home Page

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/Ezy-Parking#9]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to add the testimonial section to the home page in an appealing format for Ezy-Parking Webapp .

Feel free to be creative! And please take care of the following criteria:

- create atleast 6 dummy testimonials that slides up continuously with separate section of testimonials created in the home page before to Frequently Asked Questions. 
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of testimonial section created in video format on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/Ezy-Parking/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by Nincompup** [comment]
@prathimacode-hub  I got the issue, May I work on it?

**Comment by prathimacode-hub** [comment]
Issue assigned to @Nincompup. You can proceed.

@samyaksand, you can have a glance and come up with a new issue as this was created based on @Nincompup's request.
Issues will also be added soon.

**Comment by Nincompup** [comment]
@prathimacode-hub  I have made a PR. If u think anything to change please let me know

**Comment by prathimacode-hub** [comment]
You haven't got this issue assigned i think so.
Kindly create an issue template and get it assigned. @Nincompup
